set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set (LIBIRM_CMAKE_CXX_FLAGS -Wall -Werror)
if (NOT LLVM_ENABLE_RTTI)
  list(APPEND LIBIRM_CMAKE_CXX_FLAGS -fno-rtti)
endif()

set (LIBIRM_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include)
