set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Werror")
if (LIBIRM_BUILD_32_BITS)
  set (CMAKE_CXX_FLAGS -m32 ${CMAKE_CXX_FLAGS})
endif()

set (LIBIRM_CMAKE_CXX_FLAGS -fno-rtti)
set (LIBIRM_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include)